using ZArchiveSharp.Zstd;

namespace ZArchiveSharp.Tests;

/// <summary>
/// Committed libzstd-1.5.7 ground truth (<c>Goldens/zstd/</c>, generated by
/// <c>compression.zstd</c> one-shot <c>compress(data, level)</c>). These run
/// with no toolchain: the goldens carry the native bytes, so CI pins the
/// encoder/decoder even where python/gcc are absent. Inputs that are pure
/// phrase cycles are regenerated (<c>CycleText</c>); RNG inputs are committed
/// (<c>random8k.bin</c> seed <c>0x60D6</c>, <c>hetero64.bin</c> = 16 KiB text +
/// 8 KiB random + 8 KiB text + zero pad).
/// </summary>
public sealed class ZstdGoldenTests
{
    private static readonly byte[] Phrase =
        "The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. "u8.ToArray();

    private static string GoldensDir()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir, "CSharp_ZArchiveSharp.sln")))
            {
                return Path.Combine(dir, "ZArchiveSharp.Tests", "Goldens", "zstd");
            }

            dir = Directory.GetParent(dir)?.FullName;
        }

        throw new InvalidOperationException("Repo root not found.");
    }

    private static byte[] CycleText(int n)
    {
        var buf = new byte[n];
        for (var i = 0; i < n; i++)
        {
            buf[i] = Phrase[i % Phrase.Length];
        }

        return buf;
    }

    public static TheoryData<string, int, int> Cases()
    {
        var data = new TheoryData<string, int, int>();
        foreach (var name in new[] { "text8k", "random8k", "hetero64", "text200k" })
        {
            foreach (var level in new[] { 1, 6, 19 })
            {
                data.Add(name, level, name switch
                {
                    "text8k" => 8192,
                    "random8k" => 8192,
                    "hetero64" => 65536,
                    _ => 200000,
                });
            }
        }

        return data;
    }

    private static byte[] LoadInput(string dir, string name)
    {
        return name switch
        {
            "text8k" => CycleText(8192),
            "text200k" => CycleText(200000),
            "random8k" => File.ReadAllBytes(Path.Combine(dir, "random8k.bin")),
            "hetero64" => File.ReadAllBytes(Path.Combine(dir, "hetero64.bin")),
            _ => throw new ArgumentOutOfRangeException(nameof(name)),
        };
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void OurEncode_MatchesNativeGolden(string name, int level, int size)
    {
        var dir = GoldensDir();
        var input = LoadInput(dir, name);
        Assert.Equal(size, input.Length);
        var golden = File.ReadAllBytes(Path.Combine(dir, $"{name}_l{level}.zst"));

        var ours = new ZstdCompressor(ZstdCompressionOptions.FromLevel(level)).CompressBlock(input);
        Assert.Equal(golden, ours);
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void OurDecode_MatchesGoldenInput(string name, int level, int _)
    {
        var dir = GoldensDir();
        var expected = LoadInput(dir, name);
        var golden = File.ReadAllBytes(Path.Combine(dir, $"{name}_l{level}.zst"));

        var decoded = ZstdCompressor.DecompressFrame(golden, maxSize: expected.Length);
        Assert.Equal(expected, decoded);
    }
}